export const professionOptions = [
  { value: "engineer", label: "Mühəndis" },
  { value: "doctor", label: "Həkim" },
  { value: "teacher", label: "Müəllim" },
  { value: "lawyer", label: "Hüquqşünas" },
  { value: "programmer", label: "Proqramçı" },
  { value: "economist", label: "İqtisadçı" },
  { value: "architect", label: "Memar" },
  { value: "accountant", label: "Mühasib" },
  { value: "marketer", label: "Marketoloq" },
  { value: "journalist", label: "Jurnalist" },
  { value: "translator", label: "Tərcüməçi" },
  { value: "designer", label: "Dizayner" },
  { value: "police_officer", label: "Polis" },
  { value: "military", label: "Hərbçi" },
  { value: "oil_worker", label: "Neftçi" },
  { value: "mechanic", label: "Mexanik" },
  { value: "it_specialist", label: "İT üzrə mütəxəssis" },
  { value: "data_analyst", label: "Data analitiki" },
  { value: "psychologist", label: "Psixoloq" },
  { value: "lab_assistant", label: "Laborant" },
  { value: "student", label: "Tələbə" },
  { value: "unemployed", label: "İşsiz" },
];
