import * as XLSX from "xlsx";
import { formatDate, readField, formatEducationLevel, formatProfession } from "./formatters";

export const exportAcceptedApplicantsToExcel = (
  data,
  filename = "accepted-applicants.xlsx"
) => {
  const excelData = data.map((user, index) => ({
    "#": index + 1,
    ID: readField(user, "user_id"),
    Ad: readField(user, "name"),
    Soyad: readField(user, "surname"),
    "Ata adı": readField(user, "father_name", "fatherName"),
    "Doğum tarixi": formatDate(readField(user, "date_of_birth", "dateOfBirth")),
    Cins: readField(user, "sex"),
    "Doğum yeri": readField(user, "place_of_birth"),
    "Seriya nömrəsi": readField(user, "national_serial_num"),
    FIN: readField(user, "national_id_num"),
    Telefon: readField(user, "phone_number", "phoneNumber"),
    Email: readField(user, "email"),
    "Təhsil səviyyəsi": formatEducationLevel(
      readField(user, "education_level", "educationLevel"),
    ),
    Universitet: readField(user, "university"),
    Peşə: formatProfession(readField(user, "profession")),
    "Gizli açar": readField(user, "secret_key", "secretKey"),
    "Qəbul tarixi": formatDate(readField(user, "accepted_at")),
  }));

  const workbook = XLSX.utils.book_new();
  const worksheet = XLSX.utils.json_to_sheet(excelData);

  const columnWidths = [
    { wch: 5 }, // #
    { wch: 12 }, // ID
    { wch: 15 }, // Ad
    { wch: 15 }, // Soyad
    { wch: 15 }, // Ata adı
    { wch: 12 }, // Doğum tarixi
    { wch: 8 }, // Cins
    { wch: 20 }, // Doğum yeri
    { wch: 15 }, // Seriya nömrəsi
    { wch: 18 }, // Şəxsiyyət vəsiqəsi
    { wch: 15 }, // Telefon
    { wch: 25 }, // Email
    { wch: 18 }, // Təhsil səviyyəsi
    { wch: 25 }, // Universitet
    { wch: 20 }, // Peşə
    { wch: 25 }, // Gizli açar
    { wch: 15 }, // Qəbul tarixi
  ];

  worksheet["!cols"] = columnWidths;

  const headerRange = XLSX.utils.decode_range(worksheet["!ref"]);
  for (let col = headerRange.s.c; col <= headerRange.e.c; col++) {
    const cellAddress = XLSX.utils.encode_cell({ r: 0, c: col });
    if (!worksheet[cellAddress]) continue;

    worksheet[cellAddress].s = {
      font: { bold: true, color: { rgb: "FFFFFF" } },
      fill: { fgColor: { rgb: "366F6B" } },
      alignment: { horizontal: "center" },
    };
  }

  XLSX.utils.book_append_sheet(workbook, worksheet, "Qəbul edilən müraciətlər");

  const metaData = [
    ["Export Information", ""],
    ["Export Date", new Date().toLocaleString("az-AZ")],
    ["Total Records", data.length],
    ["Generated By", "Admin Dashboard"],
    ["", ""],
    ["Column Descriptions", ""],
    ["ID", "İstifadəçi identifikatoru"],
    ["Ad", "İstifadəçinin adı"],
    ["Soyad", "İstifadəçinin soyadı"],
    ["Ata adı", "İstifadəçinin ata adı"],
    ["Doğum tarixi", "İstifadəçinin doğum tarixi"],
    ["Cins", "İstifadəçinin cinsi"],
    ["Doğum yeri", "İstifadəçinin doğum yeri"],
    ["Seriya nömrəsi", "Şəxsiyyət vəsiqəsinin seriya nömrəsi"],
    ["Şəxsiyyət vəsiqəsi", "Şəxsiyyət vəsiqəsinin FIN nömrəsi"],
    ["Telefon", "Əlaqə telefonu"],
    ["Email", "Elektron poçt ünvanı"],
    ["Təhsil səviyyəsi", "Təhsil səviyyəsi"],
    ["Universitet", "Universitet/Təhsil müəssisəsi"],
    ["Peşə", "Peşə/İxtisas"],
    ["Gizli açar", "Sistem tərəfindən yaradılan gizli açar"],
    ["Qəbul tarixi", "Müraciətin qəbul edildiyi tarix"],
  ];

  const metaWorksheet = XLSX.utils.aoa_to_sheet(metaData);
  metaWorksheet["!cols"] = [{ wch: 25 }, { wch: 40 }];

  XLSX.utils.book_append_sheet(workbook, metaWorksheet, "Məlumat");
  XLSX.writeFile(workbook, filename);

  return true;
};
